Repository naman1102/KanBan-Hacktober, pull requests merged in 2022-10, with the labels that each got.

#6 Resolved: Login UI (Flutter application)
  .gitignore
  .metadata
  .vscode/c_cpp_properties.json
  .vscode/tasks.json
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/login_screen/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  android/build.gradle
  assets/fonts/Montserrat-Bold.otf
  assets/fonts/Montserrat-Regular.otf
  assets/fonts/Montserrat-SemiBold.otf
  assets/images/facebook.png
  assets/images/google.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/controller/auth_controller.dart
  lib/hello_pranshu2105.cpp
  lib/hello_pranshu2105.exe
  lib/main.dart
  lib/screens/home_screen/home_screen.dart
  lib/screens/login_screen/animations/change_screen_animation.dart
  lib/screens/login_screen/components/bottom_text.dart
  lib/screens/login_screen/components/center_widget/center_widget.dart
  lib/screens/login_screen/components/center_widget/center_widget_clipper.dart
  lib/screens/login_screen/components/center_widget/center_widget_painter.dart
  lib/screens/login_screen/components/login_content.dart
  lib/screens/login_screen/components/top_text.dart
  lib/screens/login_screen/login_screen.dart
  lib/utils/constant.dart
  lib/utils/constants.dart
  lib/utils/helper_functions.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: hacktober-accepted

#7 Resolved: Improve README.md
  README.md
Labels: documentation, hacktober-accepted

#10 chore : update color them for easily changeable
  lib/config/AppTheme.dart
  lib/main.dart
  lib/screens/login_screen/components/bottom_text.dart
  lib/screens/login_screen/components/login_content.dart
Labels: hacktober-accepted

#14 Created Code flow: Suggest Flow for KanBan App development (Flutter Application) #3
  Code_flow.md
  README.md
Labels: documentation, enhancement, hacktober-accepted

#15 Updated code flow: Suggest Flow for KanBan App development (Flutter Application) #3
  Code_flow.md
Labels: enhancement, hacktober-accepted
